name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hello-devops.sh script
        run: bash ./04-ci-cd-github-actions/hello-devops.sh

