apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
  namespace: cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: pv271994/cicd-app:latest
          ports:
            - containerPort: 5000
