apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  namespace: cicd-app
spec:
  type: NodePort
  selector:
    app: cicd-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
