apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-demo
spec:
  containers:
    - name: secret-app
      image: busybox
      command: ["sh", "-c", "echo USER=$USERNAME && echo PASS=$PASSWORD && sleep 3600"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: PASSWORD
