name: GitHub Secrets Demo

on:
  push:
    paths:
      - '04-ci-cd-github-actions/04-secrets-demo.sh'
      - '.github/workflows/04-secrets.yml'

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script with secret
        run: bash 04-ci-cd-github-actions/04-secrets-demo.sh
