name: Artifacts Upload/Download Demo

on:
  push:
    paths:
      - "04-ci-cd-github-actions/05-artifacts-demo.sh"
      - ".github/workflows/05-artifacts.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Artifact Script
        run: bash 04-ci-cd-github-actions/05-artifacts-demo.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: reports/

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-reports

      - name: List downloaded files
        run: ls -R
