name: Artifacts Upload and Download

on:
  push:
    paths:
      - .github/workflows/05-artifacts.yml
      - 04-ci-cd-github-actions/05-artifacts-demo.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: bash 04-ci-cd-github-actions/05-artifacts-demo.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: 04-ci-cd-github-actions/build_output.txt

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Show artifact content
        run: cat build_output.txt
