name: Scheduled Workflow Demo

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 12:00 AM UTC

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "Workflow ran on: $(date)"

      - name: Run script
        run: bash 04-ci-cd-github-actions/11-schedule-demo.sh
