name: Build & Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" \
             | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        working-directory: 06-kubernetes/kubernetes_practicals/cicd-app
        run: |
          docker build -t yourdockerhubusername/cicd-app:latest .
          docker push yourdockerhubusername/cicd-app:latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace cicd-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f 06-kubernetes/kubernetes_practicals/cicd-app/k8s/deployment.yaml
          kubectl apply -f 06-kubernetes/kubernetes_practicals/cicd-app/k8s/service.yaml
