name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, ${{ inputs.username }}! This is a reusable workflow!"
